instances:
  path:
    # Default instance path for all experiments, can be overridden.
    default: 'instances/small'

    # Override default instance path only for the experiment declared in file PreliminarExperiment.java
    # If an experiment does not have a specific path the default will be used. Example:
    # PreliminarExperiment: './instances/preliminar'


solver:
  # Global random seed to ensure reproducibility
  seed: 1234

  # Random generator provider, see RandomType enum for a full list of available implementations
  random-type: default

  # Which experiments should be executed? .* --> All.
  # Experiment names default to the class name in which they are declared unless overridden.
  # Tip, you may use a Regex, example: Preeliminar.*
  experiments: 'Constructive.*'

  # How many times should each experiment be repeated. Recommended a minimum of 30
  repetitions: 100_000

  # Use parallel executor DISABLE IF THE ALGORITHM IS ALREADY PARALLELIZED
  # Valid Values: true, false
  parallelExecutor: true

  # Number of workers to use if parallelExecutor is enabled
  # any number between 1 and MAX_INT, or -1 to automatically decide at runtime (available threads / 2)
  nWorkers: -1

  # Execute benchmark before starting solver? False to skip benchmark.
  benchmark: true

  #### Autoconfig properties
  # Tree depth when using automatic configuration
  tree-depth: 1000
  # Max derivation repetitions when using automatic configuration
  # If 0, disables recursion.
  # As an example: with 1, an Improver may be replaced by a SequentialImprover,
  # which may be replaced again by SequentialImprover, for a total improver sequence length of 4.
  max-derivation-repetition: 1
  # Number of experiments to execute for each parameter available for tuning after transformed into irace space.
  experiments-per-parameter: 200
  # Minimum number of experiments to run, if the number of parameters is lower than this value,
  # the number of experiments will be equal to this value
  minimum-number-of-experiments: 10000
  # For each solution generated by any algorithm, ignore this millis in the area calculation.
  # WARNING: Any algorithm that does not report an o.f value before this limit is reached is considered invalid
  ignore-initial-millis: 10000
  # Area will be measured in interval [ignoreInitialMillis, ignoreInitialMillis+intervalDurationMillis]
  # Algorithms are asked to stop (politely first, killed after) after the ignoreInitialMillis+intervalDurationMillis mark is reached.
  # Even if they execute for a longer time, their improvements to the objective function will not be considered.
  interval-duration-millis: 50000
  # Scale o.f AUC using natural logarithm
  log-scale-area: true
  #### End autoconfig properties

  # Enable or disable metrics tracking. Force enabled if using autoconfig.
  metrics: false

# Enable irace integration? Check IRACE Wiki section before enabling
irace:
  enabled: false

  # False: (EXPERIMENTAL) use GraalVM implementation, does not need R installed locally
  # True: (RECOMMENDED) Use shell to execute R scripts, R / Rscript need to be locally installed and in path
  shell: true

  # Maximum number of algorithm executions
  maxExperiments: 10000

# Event system integrations/configuration
event:
  # Stop webserver after all work is done?
  # If true, app will stop after all experiments finish executing, and front end will stop loading. (DEFAULT)
  # If false, webserver will keep executing, and front will be available until manually stopped by the user.
  webserver:
    stopOnExecutionEnd: true

  # Enable message notifications to any given user on experiment end. See
  telegram:
    # If false bot is completely disabled
    enabled: false
    # Token returned by @BotFather
    token: ''
    # Chat where we will send notifications
    chatId: ''

# Experiment execution DOES NOT (usually) END if an uncontrolled exception is propagated
# The error is logged, and we try to keep solving
errors:
  # Write exceptions and errors with their context to disk?
  errorsToFile: true

  # Path where all errors or exceptions encountered during experiment execution will be exported
  folder: 'errors'

# Set default server port (change if there is multiple Mork instances running)
server:
    port : 8080
